def show_menu():
    print("\n========== STUDENT MANAGEMENT ==========")
    print("1. Thêm sinh viên")
    print("2. Hiển thị danh sách")
    print("3. Tìm kiếm sinh viên")
    print("4. Cập nhật sinh viên")
    print("5. Xóa sinh viên")
    print("6. Lưu dữ liệu")
    print("7. Đọc dữ liệu")
    print("8. Thống kê học lực")
    print("9. Sắp xếp theo GPA")
    print("10. Tìm theo tên")
    print("11. Tìm theo ngành")
    print("12. Xuất CSV")
    print("0. Thoát")
    print("========================================")